# Adaptation of colors from WezTerm to Alacritty in TOML format

# [[colors.indexed_colors]]
# color = "#ffa066"  # Additional color
# index = 16
#
# [[colors.indexed_colors]]
# color = "#ff5d62"  # Additional color
# index = 17
#
# [colors.bright]
# black = "#727169"   # Bright ANSI Black
# blue = "#7fb4ca"    # Bright ANSI Blue
# cyan = "#7aa89f"    # Bright ANSI Cyan
# green = "#98bb6c"   # Bright ANSI Green
# magenta = "#938aa9" # Bright ANSI Magenta
# red = "#e82424"     # Bright ANSI Red
# white = "#dcd7ba"   # Bright ANSI White
# yellow = "#e6c384"  # Bright ANSI Yellow
#
# [colors.cursor]
# cursor = "#c8c093"  # Cursor color
# text = "#c8c093"    # Cursor text color
#
# [colors.normal]
# black = "#090618"   # ANSI Black
# blue = "#7e9cd8"    # ANSI Blue
# cyan = "#6a9589"    # ANSI Cyan
# green = "#76946a"   # ANSI Green
# magenta = "#957fb8" # ANSI Magenta
# red = "#c34043"     # ANSI Red
# white = "#c8c093"   # ANSI White
# yellow = "#c0a36e"  # ANSI Yellow
#
# [colors.primary]
# background = "#181616"  # Background color
# foreground = "#dcd7ba"  # Foreground color
#
# [colors.selection]
# background = "#2d4f67"  # Selection background color
# text = "#c8c093"        # Selection text color

# mariana theme
# [[colors.indexed_colors]]
# color = "#ff5c57"  # Rojo
# index = 16
#
# [[colors.indexed_colors]]
# color = "#ffbd69"  # Naranja
# index = 17
#
# [colors.bright]
# black = "#5b5b5b"   # Negro Brillante
# blue = "#61afef"    # Azul Brillante
# cyan = "#56b6c2"    # Cian Brillante
# green = "#98c379"   # Verde Brillante
# magenta = "#c678dd" # Magenta Brillante
# red = "#e06c75"     # Rojo Brillante
# white = "#abb2bf"   # Blanco Brillante
# yellow = "#e5c07b"  # Amarillo Brillante
#
# [colors.cursor]
# cursor = "#528bff"  # Color del cursor
# text = "#ffffff"     # Color del texto del cursor
#
# [colors.normal]
# black = "#282c34"   # Negro ANSI
# blue = "#61afef"    # Azul ANSI
# cyan = "#56b6c2"    # Cian ANSI
# green = "#98c379"   # Verde ANSI
# magenta = "#c678dd" # Magenta ANSI
# red = "#e06c75"     # Rojo ANSI
# white = "#abb2bf"   # Blanco ANSI
# yellow = "#e5c07b"  # Amarillo ANSI
#
# [colors.primary]
# background = "#282c34"  # Color de fondo
# foreground = "#abb2bf"  # Color de primer plano
#
# [colors.selection]
# background = "#3e4451"  # Color de fondo de selecci贸n
# text = "#ffffff"        # Color de texto de selecci贸n

[[colors.indexed_colors]]
color = "#ff8a7a"  # Rojo
index = 16

[[colors.indexed_colors]]
color = "#ffbd69"  # Naranja
index = 17

[colors.bright]
black = "#43454b"   # Negro Brillante
blue = "#4ec4e6"    # Azul Brillante
cyan = "#78c2b3"    # Cian Brillante
green = "#83c9bc"   # Verde Brillante
magenta = "#ff85b8" # Magenta Brillante
red = "#ff8170"     # Rojo Brillante
white = "#dfdfe0"   # Blanco Brillante
yellow = "#d9c668"  # Amarillo Brillante

[colors.cursor]
cursor = "#4f5052"  # Color del cursor
text = "#ecedf0"     # Color del texto del cursor

[colors.normal]
black = "#282c34"   # Negro ANSI
blue = "#4eb0cc"    # Azul ANSI
cyan = "#b281eb"    # Cian ANSI
green = "#78c2b3"   # Verde ANSI
magenta = "#ff7ab2" # Magenta ANSI
red = "#ff8a7a"     # Rojo ANSI
white = "#ffffff"    # Blanco ANSI
yellow = "#d9c97c"  # Amarillo ANSI

[colors.primary]
background = "#1e1e1e"  # Color de fondo
foreground = "#dfdfe0"  # Color de primer plano

[colors.selection]
background = "#3e4451"  # Color de fondo de selecci贸n
text = "#ffffff"        # Color de texto de selecci贸n


[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 16

[font.normal]
family = "IosevkaTerm NF"

[window]
option_as_alt = "Both"
opacity = 1

[env]
