# Adaptation of colors from WezTerm to Alacritty in TOML format

# [[colors.indexed_colors]]
# color = "#ffa066"  # Additional color
# index = 16
#
# [[colors.indexed_colors]]
# color = "#ff5d62"  # Additional color
# index = 17
#
# [colors.bright]
# black = "#727169"   # Bright ANSI Black
# blue = "#7fb4ca"    # Bright ANSI Blue
# cyan = "#7aa89f"    # Bright ANSI Cyan
# green = "#98bb6c"   # Bright ANSI Green
# magenta = "#938aa9" # Bright ANSI Magenta
# red = "#e82424"     # Bright ANSI Red
# white = "#dcd7ba"   # Bright ANSI White
# yellow = "#e6c384"  # Bright ANSI Yellow
#
# [colors.cursor]
# cursor = "#c8c093"  # Cursor color
# text = "#c8c093"    # Cursor text color
#
# [colors.normal]
# black = "#090618"   # ANSI Black
# blue = "#7e9cd8"    # ANSI Blue
# cyan = "#6a9589"    # ANSI Cyan
# green = "#76946a"   # ANSI Green
# magenta = "#957fb8" # ANSI Magenta
# red = "#c34043"     # ANSI Red
# white = "#c8c093"   # ANSI White
# yellow = "#c0a36e"  # ANSI Yellow
#
# [colors.primary]
# background = "#181616"  # Background color
# foreground = "#dcd7ba"  # Foreground color
#
# [colors.selection]
# background = "#2d4f67"  # Selection background color
# text = "#c8c093"        # Selection text color

# mariana theme
# [[colors.indexed_colors]]
# color = "#ff5c57"  # Rojo
# index = 16
#
# [[colors.indexed_colors]]
# color = "#ffbd69"  # Naranja
# index = 17
#
# [colors.bright]
# black = "#5b5b5b"   # Negro Brillante
# blue = "#61afef"    # Azul Brillante
# cyan = "#56b6c2"    # Cian Brillante
# green = "#98c379"   # Verde Brillante
# magenta = "#c678dd" # Magenta Brillante
# red = "#e06c75"     # Rojo Brillante
# white = "#abb2bf"   # Blanco Brillante
# yellow = "#e5c07b"  # Amarillo Brillante
#
# [colors.cursor]
# cursor = "#528bff"  # Color del cursor
# text = "#ffffff"     # Color del texto del cursor
#
# [colors.normal]
# black = "#282c34"   # Negro ANSI
# blue = "#61afef"    # Azul ANSI
# cyan = "#56b6c2"    # Cian ANSI
# green = "#98c379"   # Verde ANSI
# magenta = "#c678dd" # Magenta ANSI
# red = "#e06c75"     # Rojo ANSI
# white = "#abb2bf"   # Blanco ANSI
# yellow = "#e5c07b"  # Amarillo ANSI
#
# [colors.primary]
# background = "#282c34"  # Color de fondo
# foreground = "#abb2bf"  # Color de primer plano
#
# [colors.selection]
# background = "#3e4451"  # Color de fondo de selección
# text = "#ffffff"        # Color de texto de selección

[[colors.indexed_colors]]
color = "#F92672"  # Rojo (Diff Deleted)
index = 16

[[colors.indexed_colors]]
color = "#A6E22E"  # Verde (Diff Inserted)
index = 17

[colors.bright]
black = "#43454b"   # Negros oscuros de fondo adaptados
blue = "#6CF4FD"    # Azul brillante (Clases y soporte)
cyan = "#4CBCC8"    # Cian brillante (Funciones)
green = "#6FDCF5"   # Verde brillante (Constantes)
magenta = "#FB7A80" # Magenta brillante (Cadenas de texto)
red = "#F2777A"     # Rojo brillante (Errores y palabras clave)
white = "#EDEEF3"   # Blanco brillante (Operadores)
yellow = "#EBE185"  # Amarillo brillante (Números)

[colors.cursor]
cursor = "#CCCCCC"  # Color del cursor (Caret)
text = "#393939"    # Texto de línea resaltada (Line Highlight)

[colors.normal]
black = "#1E1E1E"   # Fondo normal (Background)
blue = "#6CF4FD"    # Azul ANSI (Clases)
cyan = "#4CBCC8"    # Cian ANSI (Funciones)
green = "#6FDCF5"   # Verde ANSI (Constantes)
magenta = "#FB7A80" # Magenta ANSI (Cadenas)
red = "#F2777A"     # Rojo ANSI (Errores)
white = "#CCCCCC"   # Blanco ANSI (Foreground)
yellow = "#EBE185"  # Amarillo ANSI (Números)

[colors.primary]
background = "#1E1E1E"  # Color de fondo
foreground = "#CCCCCC"  # Color de primer plano

[colors.selection]
background = "#515151"  # Fondo de selección
text = "#CCCCCC"        # Texto de selección


[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 16

[font.normal]
family = "IosevkaTerm NF"

[window]
option_as_alt = "Both"
opacity = 1
dimensions = { columns = 165, lines = 45 }

[env]
